name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Checking and cleaning up disk space..."
            # Docker 이미지와 컨테이너 정리
            docker image prune -a -f
            docker container prune -f
            docker volume prune -f
            docker builder prune -a -f

            # 로그 파일 정리
            sudo find /var/lib/docker/containers/ -type f -name "*.log" -exec truncate -s 0 {} \;

            # 디스크 사용량 확인
            df -h

            echo "SSH connection successful!"
            set -e  # 스크립트 실행 중 오류 발생 시 중지
            cd ~/LifeOnHana_AI
            echo "Pulling latest code..."
            git fetch https://yena45:${{ secrets.GH_TOKEN }}@github.com/Hanaro-JSON/LifeOnHana_AI.git develop
            git reset --hard FETCH_HEAD
            echo "Stopping existing containers..."
            docker-compose down --remove-orphans
            echo "Building Docker images..."
            docker-compose build --no-cache
            echo "Starting new containers..."
            docker-compose up -d
            echo "Deployment completed successfully."
