name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            export DOCKER_BUILDKIT=1
            echo "Checking and cleaning up disk space..."
            df -h
            docker image prune -a -f
            docker container prune -f
            docker volume prune -f
            docker builder prune -a -f

            echo "SSH connection successful!"
            set -e
            cd ~/LifeOnHana_AI
            echo "Pulling latest code..."
            git fetch https://yena45:${{ secrets.GH_TOKEN }}@github.com/Hanaro-JSON/LifeOnHana_AI.git develop
            git reset --hard FETCH_HEAD
            echo "Stopping existing containers..."
            docker-compose down --remove-orphans
            echo "Building Docker images with BuildKit..."
            docker-compose build --no-cache | tee docker-build.log
            echo "Starting new containers..."
            docker-compose up -d
            echo "Deployment completed successfully."
